apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-web-autoscaling
  labels:
    app: my-k8s-application
    env: prod
    owner: led
spec:
  replicas: 2
  selector:
    matchLabels:
      project: project3
  template:
    metadata:
      labels:
        project: project3
    spec:
      containers:
        - name: project3-web
          image: httpd
          ports:
            containerPort: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-autoscaling
  spec:
    scaleTargetRef:
      apiVersion: apps/v2
      kind: Deployment
      name: my-web-autoscaling
    minReplicas: 2
    maxReplicas: 5
    metrics:
      - type: Resource
        resource:
          name: cpu
          targetAverageUtilization: 70
      -type: Resource
        resource:
          name: memory
          targetAverageUtilization: 80
