apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: ingress-hosts

spec:
  rules:
  - host: www.my-site.com
    http:
      paths:
        - backend:
          serviceName: main
          servicePort: 80
  - host: web1.my-site.com
    http:
      paths:
        - backend:
          serviceName: web1
          servicePort: 80
  - host: web2.my-site.com
    http:
      paths:
        - backend:
          serviceName: web2
          servicePort: 80
  - host: tomcat.my-site.com
    http:
      paths:
        - backend:
          serviceName: tomcat
          servicePort: 8080
