apiVersion: v1
kind: Pod
metadata:
  name: my-web
  labels:
    env: prod
    app: main
    tier: frontend
    owner: led
spec:
  containers:
    - name: container-web
      image: nginx
      ports:
        - containerPort: 80
