"""Send some metric to pushgateway"""
from datetime import datetime

from prometheus_client import CollectorRegistry, Gauge, push_to_gateway

PUSHGATEWAY = 'http://localhost:9091'
JOB_NAME = 'python_job'
INSTANCE_NAME = 'my_instance'


class SomeMetric:
    """Create metric and send to pushgateway"""

    def __init__(self, name: str, description: str, value: str, labels: dict):
        self.name = name
        self.description = description
        self.value = value
        self.labels = labels

    @property
    def value(self):
        """Value of metric"""
        return self.__value

    @value.setter
    def value(self, new_value):
        try:
            self.__value = float(new_value)
        except ValueError:
            print(f'ERROR: send metric {self.name} error: {new_value} at {datetime.now()}')
            self.__value = -1

    def send_metric(self):
        """Send to pushgateway"""
        registry = CollectorRegistry()

        metric = Gauge(
            name=self.name,
            documentation=self.description,
            labelnames=list(self.labels.keys()),
            registry=registry
        )

        metric.labels(**self.labels).set(self.__value)

        push_to_gateway(
            gateway=PUSHGATEWAY,
            job=JOB_NAME,
            registry=registry,
            grouping_key={'instance': INSTANCE_NAME}
        )


if __name__ == '__main__':
    item = SomeMetric(
        name='random_metric',
        description='Random metric generated by Python script',
        value=str(1.23),
        labels={
            'source': str('localhost'),
            'destination': str('ya.ru')
        }
    )
    item.send_metric()
