apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name}}-service
  labels:
    env: prod
    owner: led
spec:
  selector:
    project: {{ .Release.Name}}-project
  ports:
    - name: {{ .Release.Name}}-listener
      protocol: TCP
      port: 80
      targetPort: 80
  type: LoadBalancer
